apiVersion: v1
kind: Service
metadata:
  name: relu-service
  labels:
    app: relu

spec:
  selector:
    app: relu
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 30001
      targetPort: 30001
      nodePort: 30001

---
apiVersion: v1
kind: Service
metadata:
  name: sigmoid-service
spec:
  selector:
    app: sigmoid
  ports:
    - protocol: TCP
      port: 30000
      targetPort: 30000
      nodePort: 30000
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: softmax-service
spec:
  selector:
    app: softmax
  ports:
    - protocol: TCP
      port: 30003
      targetPort: 30003
      nodePort: 30003
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: tanh-service
spec:
  selector:
    app: tanh
  ports:
    - protocol: TCP
      port: 30002
      targetPort: 30002
      nodePort: 30002
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: linear-service
spec:
  selector:
    app: linear
  ports:
    - protocol: TCP
      port: 30004
      targetPort: 30004
      nodePort: 30004
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: mse-service
spec:
  selector:
    app: mse
  ports:
    - protocol: TCP
      port: 30005
      targetPort: 30005
      nodePort: 30005
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: cross-entropy-loss-service
spec:
  selector:
    app: cross-entropy-loss
  ports:
    - protocol: TCP
      port: 30006
      targetPort: 30006
      nodePort: 30006
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: sgd-service
spec:
  selector:
    app: sgd
  ports:
    - protocol: TCP
      port: 30007
      targetPort: 30007
      nodePort: 30007
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: adagrad-service
spec:
  selector:
    app: adagrad
  ports:
    - protocol: TCP
      port: 30008
      targetPort: 30008
      nodePort: 30008
  type: LoadBalancer
