version: "3.8"

services:
  sigmoid:
    build: nn/sigmoid
    image: sigmoid:1.0
    ports:
      - 30000:30000

  relu:
    build: nn/relu
    image: relu:1.0
    ports:
      - 30001:30001

  tanh:
    build: nn/tanh
    image: tanh:1.0
    ports:
      - 30002:30002

  softmax:
    build: nn/softmax
    image: softmax:1.0
    ports:
      - 30003:30003

  linear:
    build: nn/linear
    image: linear:1.0
    ports:
      - 30004:30004

  mse:
    build: nn/mse
    image: mse:1.0
    ports:
      - 30005:30005

  cross_entropy_loss:
    build: nn/cross_entropy_loss
    image: cross_entropy_loss:1.0
    ports:
      - 30006:30006

  adagrad:
    build: optim/adagrad
    image: adagrad:1.0
    ports:
      - 30008:30008

  sgd:
    build: optim/sgd
    image: sgd:1.0
    ports:
      - 30007:30007
